### ISSUE TITLE
The legend axis label is difficult to read

### ISSUE THREAD

**Issue by bleathem** [bleathem/locationforcelayout#12]
The color legend is currently in the bottom left corner of the map, and the "Time" label above the arrow is difficult to see.  We could either:
1. place a light-colored box behind the legend to improve visibility
2. place the legend on the left-hand-side. There appears to be space for it beside the clock/node/count info boxes.

Thoughts @andresgalante?

**Comment by andresgalante** [comment]
@bleathem I was leaving that for later. When we get the real map we will know where and how to show the legend better. Makes sense?

**Comment by bleathem** [comment]
That makes sense.  Maybe we can just give it a white background for now then?  That way it'll at least be legible as we ask for feedback.

**Comment by andresgalante** [comment]
yeap, good idea. I'll do that now

**Comment by bleathem** [comment]
Thanks @andresgalante
