### ISSUE TITLE
Remove unnecessary js libraries

### ISSUE THREAD

**Issue by bleathem** [bleathem/locationforcelayout#15]
At some point jQuery, bootstrap, and patternfly libraries were introduced.  @andresgalante are the used for any specific purpose?  Any complaints if I remove them?

**Comment by andresgalante** [comment]
We are using some patternfly and some bootsrap and none jquery. I am only importing the parts I am using on styles.less to keep the css file as small as possible:
https://github.com/bleathem/locationforcelayout/blob/master/src/less/styles.less
If you want I can pick the less files we are using and put them on a different folder.
