### ISSUE TITLE
Consistently style the demo visualtizations

### ISSUE THREAD

**Issue by bleathem** [bleathem/locationforcelayout#26]
I've re-factored the client folder to better delineate the different visualisations.  Each of the visualisations should be styled consistently, placing shared resources in the `/client/common` folder.

**Comment by bleathem** [comment]
@andresgalante can you take care of this one?

**Comment by andresgalante** [comment]
Excellent, this is much better. I'll take a look at it tomorrow. Thanks!

**Comment by bleathem** [comment]
Thanks @andresgalante, I merged PR #27.  I've re-factored the color settings of the "winners" borders and fills into the style sheet, feel free to tweak those as required.

I noticed the branding at the top says "Red Hat Summit 2015 Force Layout".  We should change that, possibly to "Red Hat Summit 2015 Middleware Keynote Demo" if we want it to be the same across all viz, or we can name it individually for each visualisation.

**Comment by bleathem** [comment]
Also the index page: http://beacon.jbosskeynote.com/ needs a little TLC.

**Comment by andresgalante** [comment]
@bleathem yeap, we do have a favicon, we can use the same as in the mobile app. About names, I'll change it to "Red Hat Summit 2015 Middleware Keynote Demo" for all of them and we see if we need individual names later on.

I'll spend tomorrow working on this all day. If there is anything else you can think of let me know.

**Comment by bleathem** [comment]
@andresgalante i think the favicon is the only things still holding this issue open.

**Comment by andresgalante** [comment]
@bleathem we do have favicons
https://github.com/bleathem/locationforcelayout/tree/master/client/common/favicon

**Comment by bleathem** [comment]
Ah ok.  We'll just have to copy one to the root web folder so the browsers can find it.  I'll take care of that.

**Comment by bleathem** [comment]
Oh I see, you set the path via:

```
 <link rel="shortcut icon" href="/common/favicon/img/favicon.ico">
```

That path just needs to be corrected, as the `img` subfolder doesn't exist.

**Comment by bleathem** [comment]
Corrected the path with:

```
ack common/favicon/img -l | xargs sed -i 's|/common/favicon/img/|/common/favicon/|g'
```

Thanks @andresgalante!
