### ISSUE TITLE
Colors on hex

### ISSUE THREAD

**Issue by andresgalante** [bleathem/locationforcelayout#30]
@bleathem each node changes colores to a darker blue. What does each state mean?
Maybe we can change their colors to represent their state.

Can we also change the way we display the 6 winners? is its easy I can tweack it, if not I can send you a mockup next week when I am back home

thanks brain!

**Comment by andresgalante** [comment]
@bleathem I'll choose colors for state changes:
- awaiting (initial state)
- pending
- running
- live
- ready
- hitting an actual URL on the launched container

**Comment by bleathem** [comment]
Your impl looks good.  We can close this issue.  I've opened #40 to add a legend explaining what the colors mean.
