### ISSUE TITLE
The beaconEvents_processed feed does not have a timestamp property set

### ISSUE THREAD

**Issue by bleathem** [bleathem/locationforcelayout#31]
Currently setting the timestamp to the current time as a fallback.

@mattf can you make sure the timestamp porperty gets as a result of the Spark processing?

**Comment by mattf** [comment]
added in https://github.com/mattf/taiol/commit/dfdde9f33f075e85cea8e505e536e0376cb3e8d3

**Comment by bleathem** [comment]
Thanks @mattf
